apiVersion: v2
version: 5.0.0
appVersion: 3.0.0
description: A Helm chart to help backup MySQL databases using mysqldump
name: mysqldump
keywords:
- mysql
- mysqldump
- backup
home: https://www.mysql.com/
icon: https://www.mysql.com/common/logos/logo-mysql-170x115.png
sources:
- https://github.com/ucraft-com/helm-charts
- https://dev.mysql.com/doc/refman/5.7/en/mysqldump.html
maintainers:
- name: mher
  email: mher.poghosyan@ucraft.com
type: application

