apiVersion: v2
name: karrio
description: A karrio Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "2024.2.rc4"
dependencies:
  - name: redis
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 18.12.1
    condition: redis.enabled
  - name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 14.0.4
    condition: postgresql.enabled
maintainers:
  - name: Mher Poghosyan