replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: 1.21

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

deployment:
  volumes:
    enabled: false
  extraVolumeMounts: []
extraVolumes: []
service:
  enabled: true
  name: http
  type: ClusterIP
  port: 80
  protocol: TCP

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: host.name.com
      paths:
      - path: /*
        backend:
          serviceName: ssl-redirect
          servicePort: use-annotation
      - backend:
          serviceName: uc-application
          servicePort: 80
        path: /*
  tls: []

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nginx:
  enabled: false
  image:
    repository: nginx
    pullPolicy: IfNotPresent
    tag: "1.19"

  resources: {}
  extraVolumeMounts: []
  healthcheck:
    enabled: false
    period: 5
    path: /health
  config: |
    daemon            off;
    worker_processes  2;
    user              www-data;
    events {
        use           epoll;
        worker_connections  128;
    }
    error_log         logs/error.log info;
    http {
        server_tokens off;
        include       mime.types;
        charset       utf-8;
        access_log    logs/access.log  combined;
        server {
            server_name   localhost;
            listen        127.0.0.1:80;

            error_page    500 502 503 504  /50x.html;

            location      / {
                root      html;
            }

        }

    }


  exporter:
    enabled: false

    image:
      repository: nginx/nginx-prometheus-exporter
      pullPolicy: IfNotPresent
      tag: "0.9.0"

    resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

config: {}

containerPort: 80

livenessProbe: {}

readinessProbe: {}
envSecretName: {}

externalsecrets: {}

secretenv:
  enabled: false
  env: |
    APP_ENV=dev

env: dev
product: application
