{{- if .Values.secrets -}}
{{ $fullName := include "ucraft-base-helm.fullname" .}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.product }}-{{ .Values.env }}
    kind: SecretStore
  target:
    name: {{ $fullName }}
    creationPolicy: Owner
  data:
  {{- range $secret := .Values.secrets }}
  - secretKey: {{ $secret }}
    remoteRef:
      key: {{ $.Values.product }}/{{ $.Values.env }}/{{ $fullName }}
      property: {{ $secret }}
  {{- end }}
{{- end }}
