apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "laravel.selectorLabels" . | nindent 6 }}
      laravel.com/pod-type: web
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "laravel.selectorLabels" . | nindent 8 }}
        laravel.com/pod-type: web
    spec:
      volumes:
        - name: app
          emptyDir: {}
        - name: env
          secret:
            secretName: {{ if .Values.app.envSecretName }} {{ .Values.app.envSecretName }} {{ else }} {{ .Release.Name }}-env {{ end }}
        - name: nginx-config
          configMap:
            name: {{ if .Values.nginx.configName }} {{ .Values.nginx.configName }} {{ else }} {{ .Release.Name }}-nginx-config {{ end }}
        - name: php-ini-config
          configMap:
            name: {{ if .Values.phpIni.configName }} {{ .Values.phpIni.configName }} {{ else }} {{ .Release.Name }}-php-ini-config {{ end }}
        - name: php-fpm-config
          configMap:
            name: {{ if .Values.phpFpmConf.configName }} {{ .Values.phpFpmConf.configName }} {{ else }} {{ .Release.Name }}-php-fpm-config {{ end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ include "laravel.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      {{- with .Values.extraInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        {{- with .Values.extraContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: php-fpm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          volumeMounts:
            - name: app
              mountPath: /app
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            - name: php-ini-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            - name: php-fpm-config
              mountPath: /usr/local/etc/php-fpm.d/laravel.conf
              subPath: laravel.conf
            {{- with .Values.app.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          {{- if .Values.app.healthcheck.enabled }}
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: {{ .Values.app.healthcheck.period }}
            periodSeconds: {{ .Values.app.healthcheck.period }}
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: {{ .Values.app.healthcheck.period }}
            periodSeconds: {{ .Values.app.healthcheck.period }}
          {{- end }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          {{- with .Values.app.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /tmp/.env /var/www/html/.env && cp -r /var/www/html/. /app && cd /var/www/html && sh deploy.sh
        {{- if .Values.scheduler.enabled }}
        - name: scheduler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            {{- toYaml .Values.scheduler.command | nindent 12 }}
          volumeMounts:
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            - name: php-ini-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            {{- with .Values.app.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- if .Values.scheduler.healthcheck.enabled }}
          readinessProbe:
            exec:
              command:
                - php
                - -v
            initialDelaySeconds: {{ .Values.scheduler.healthcheck.period }}
            periodSeconds: {{ .Values.scheduler.healthcheck.period }}
          livenessProbe:
            exec:
              command:
                - php
                - -v
            initialDelaySeconds: {{ .Values.scheduler.healthcheck.period }}
            periodSeconds: {{ .Values.scheduler.healthcheck.period }}
          {{- end }}
          resources:
            {{- toYaml .Values.scheduler.resources | nindent 12 }}
          {{- with .Values.app.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          lifecycle:
            postStart:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - cp /tmp/.env /var/www/html/.env && cp -r /var/www/html/. /app && cd /var/www/html && sh deploy.sh
        {{- end }}
        - name: nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            - name: app
              mountPath: /var/www/html
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- with .Values.nginx.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: http2
              containerPort: 8080
              protocol: TCP
          {{- if .Values.nginx.healthcheck.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.nginx.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.nginx.healthcheck.period }}
            periodSeconds: {{ .Values.nginx.healthcheck.period }}
          livenessProbe:
            httpGet:
              path: {{ .Values.nginx.healthcheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.nginx.healthcheck.period }}
            periodSeconds: {{ .Values.nginx.healthcheck.period }}
          {{- end }}
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
        {{- if .Values.app.exporter.enabled }}
        - name: php-fpm-metrics
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.app.exporter.image.repository }}:{{ .Values.app.exporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.exporter.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: php-fpm-metrics
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: php-fpm-metrics
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            periodSeconds: 1
            httpGet:
              path: /metrics
              port: php-fpm-metrics
          env:
            - name: PHP_FPM_SCRAPE_URI
              value: tcp://127.0.0.1:9001/status
            - name: PHP_FPM_WEB_LISTEN_ADDRESS
              value: ":9253"
            - name: PHP_FPM_WEB_TELEMETRY_PATH
              value: /metrics
            - name: PHP_FPM_FIX_PROCESS_COUNT
              value: "true"
            - name: PHP_FPM_LOG_LEVEL
              value: info
          ports:
            - name: php-fpm-metrics
              containerPort: 9253
              protocol: TCP
          resources:
            {{- toYaml .Values.app.exporter.resources | nindent 12 }}
        {{- end }}
        {{- if .Values.nginx.exporter.enabled }}
        - name: nginx-metrics
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.exporter.image.repository }}:{{ .Values.nginx.exporter.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.nginx.exporter.image.pullPolicy }}
          readinessProbe:
            httpGet:
              path: /metrics
              port: nginx-metrics
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /metrics
              port: nginx-metrics
            periodSeconds: 5
          startupProbe:
            failureThreshold: 120
            periodSeconds: 1
            httpGet:
              path: /metrics
              port: nginx-metrics
          env:
            - name: SCRAPE_URI
              value: http://127.0.0.1:8080/stub_status
            - name: LISTEN_ADDRESS
              value: ":9113"
            - name: TELEMETRY_PATH
              value: /metrics
          ports:
            - name: nginx-metrics
              containerPort: 9113
              protocol: TCP
          resources:
            {{- toYaml .Values.nginx.exporter.resources | nindent 12 }}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
