apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "karrio.fullname" . }}-api
  labels:
    {{- include "karrio.labels" . | nindent 4 }}
spec:
  {{- if .Values.api.minReadySeconds }}
  minReadySeconds: {{ .Values.api.minReadySeconds }}
  {{- end }}
  {{- if .Values.api.revisionHistoryLimit }}
  revisionHistoryLimit: {{ .Values.api.revisionHistoryLimit }}
  {{- end }}
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "karrio.selectorLabels" . | nindent 6 }}
  {{- if .Values.api.strategy }}
  strategy:
    {{- toYaml .Values.api.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      annotations:
        configmap: {{ .Values.api.config | toYaml | sha256sum | trunc 10 }}
      {{- with .Values.api.podAnnotations }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "karrio.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "karrio.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- if .Values.api.initContainers }}
      initContainers:
        {{- toYaml .Values.api.initContainers | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-api
          securityContext:
            {{- toYaml .Values.api.securityContext | nindent 12 }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          {{- if .Values.api.command }}
          command:
            {{- toYaml .Values.api.command | nindent 12 }}
          {{- end }}
          {{- if .Values.api.extraEnv }}
          env:
            {{- range $key, $value := .Values.api.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.api.containerPort | default 80 }}
              protocol: TCP
          {{- if .Values.api.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.api.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.api.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.api.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "karrio.fullname" . }}-api
            - secretRef:
                name: {{ include "karrio.fullname" . }}-api
                optional: true
          volumeMounts:
            {{- with .Values.api.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        {{- with .Values.api.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

