apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend-laravel.fullname" . }}
  labels:
    {{- include "backend-laravel.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "backend-laravel.selectorLabels" . | nindent 4 }}
    backend-laravel.com/pod-type: web
