apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ucraft-base-helm.fullname" . }}
  labels:
    {{- include "ucraft-base-helm.labels" . | nindent 4 }}
spec:
  {{- if .Values.minReadySeconds}}
  minReadySeconds: {{ .Values.minReadySeconds }}
  {{- end }}
  {{- if .Values.revisionHistoryLimit}}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ucraft-base-helm.selectorLabels" . | nindent 6 }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 12 }}
  {{- end }}
  template:
    metadata:
      annotations:
        configmap: {{ .Values.config | toYaml | sha256sum | trunc 8 }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ucraft-base-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ucraft-base-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.initContainers }}
      initContainers:
      {{-  toYaml .Values.initContainers | nindent 6 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if $.Values.command }}
          command:
            {{  toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.extraEnv }}
          env:
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key | quote}}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort | default 80 }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "ucraft-base-helm.fullname" . }}
            - secretRef:
                name: {{ include "ucraft-base-helm.fullname" . }}
                optional: true
          {{- if .Values.deployment.volumes.enabled }}
          volumeMounts:
            {{- if .Values.secretenv.enabled }}
            - name: env
              mountPath: {{ if .Values.secretenv.envpath }} {{ .Values.secretenv.envpath }}env {{ else }} .env {{ end }}
              subPath: .env
            {{- end }}
            {{- if .Values.deployment.volumes.extVolume }}
            {{- range $index, $element := .Values.deployment.volumes.extVolume }}
            - name: {{ coalesce $element.name (add $index 1) }}
              mountPath: {{ $element.mountPath }}
            {{- end }}
            {{- end }}
          {{- end }}
      {{- if .Values.deployment.volumes.enabled }}
      volumes:
        {{- if .Values.secretenv.enabled }}
        - name: env
          secret:
            secretName: {{ if .Values.app.envSecretName }} {{ .Values.app.envSecretName }} {{ else }} {{ .Release.Name }}-env {{ end }}
        {{ end }}
        {{- if .Values.deployment.volumes.extVolume }}
        {{- range $index, $element := .Values.deployment.volumes.extVolume }}
        - name: {{ coalesce $element.name (add $index 1) }}
          persistentVolumeClaim:
            claimName: {{ $element.persistentVolumeClaim.claimName }}
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
