{{- if .Values.externalsecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  labels:
    updatedata: {{ .Values.externalsecrets.updatedata }}
spec:
  refreshInterval: {{ .Values.externalsecrets.interval }}
  secretStoreRef:
    name: gcpsm-secretstore
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-env
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        .env: |
          {{- range $secret := .Values.externalsecrets.env }}
          {{ $secret }}="{{- printf "{{ "}}{{- printf "."}}{{ $secret }}{{- printf " }}"}}"
          {{- end }}
  data:
  {{- range $secret := .Values.externalsecrets.env }}
  - secretKey: {{ $secret }}
    remoteRef:
      key: {{ $.Values.env }}-{{ $secret }}
  {{- end }} 
{{- end }}