{{- if .Values.externalsecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  labels:
    updatedata: {{ .Values.externalsecrets.updatedata }}
spec:
  refreshInterval: {{ .Values.externalsecrets.interval }}
  secretStoreRef:
    name: gcpsm-secretstore
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-env
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.externalsecrets.secretkey }}
    remoteRef:
      key: {{ $.Values.env }}-{{ .Release.Name }}
      property: {{ .Values.externalsecrets.secretkey }}
  {{- if .Values.externalsecrets.migration -}}
  - secretKey: .migration-version
    remoteRef:
      key: {{ $.Values.env }}-migration-version
      property: .migration-version
  {{- end }}
{{- end }}
