{{- if .Values.externalsecrets.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalsecrets.interval }}
  secretStoreRef:
    name: gcpsm-secretstore
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-env
    creationPolicy: Owner
  data:
  - secretKey: {{ .Values.externalsecrets.secretkey }}
    remoteRef:
      key: {{ $.Values.env }}-{{ .Release.Name }}
{{- end }}
