{{- if .Values.cronjob.config.secrets  }}
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}-cronjob-secret
type: Opaque
data:
  {{- range $k, $v := .Values.cronjob.config.secrets }}
  {{ $k }}: "{{ $v | b64enc }}"
  {{- end }}
{{- end }}
