{{- if and .Values.persistence.create -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "backend-laravel.fullname" . }}
#  namespace: {{ .Release.Namespace }}
  labels: 
    {{- include "backend-laravel.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end -}}
